### ISSUE TITLE
Enable JACK support

### ISSUE THREAD

**Issue by Yajo** [flathub/com.obsproject.Studio#106]
Hello, thank you very much for flatpaking OBS.

These days, with pipewire, we're finally able to use all JACK apps packaged as flatpaks.

According to [OBS wiki](https://github.com/obsproject/obs-studio/wiki/Post-Production-Tools-you-can-use) and https://github.com/jp9000/obs-studio/pull/345, OBS supports JACK, but I see it's disabled here: https://github.com/flathub/com.obsproject.Studio/blob/1337120e68256437e6ff2e020e6cf54a18a7150d/com.obsproject.Studio.json#L245

Could you please enable that support? You could possibly draw inspiration from Jamulus, which is a small JACK app that was flatpaked recently and works perfectly out of the box with pipewire-jack: https://github.com/flathub/io.jamulus.Jamulus

**Comment by GeorgesStavracas** [comment]
JACK is already enabled on the Flathub Beta version of OBS Studio, but it unfortunately requires a modern PipeWire on your host (at least 0.3.10). Maybe we can go ahead and enable that on the main branch too, but I'm afraid it'll give people on old distros a feature that won't work, which can be frustrating.

**Comment by Yajo** [comment]
> the Flathub Beta version of OBS Studio

How to test that? 🤔

**Comment by GeorgesStavracas** [comment]
I think you can just run the following command:

```
$ flatpak install --user https://flathub.org/beta-repo/appstream/com.obsproject.Studio.flatpakref
```

I don't usually advertise much the beta one because it contains many bleeding edge features that won't work if you don't have a fairly updated distro. Please be careful!

**Comment by GeorgesStavracas** [comment]
I forgot to link it here but commit https://github.com/flathub/com.obsproject.Studio/commit/97ed861daa43f3a5ab521649262870fc93dac38a adds JACK (through PipeWire) support. You'll need to use PipeWire as your audio service on host. JACK itself is impossible to be Flatpaked.

**Comment by tinywrkb** [comment]
@GeorgesStavracas  you really don't need to build jack, just get the headers and add a proper pkgconfig.  
[This is what I've done previously](https://github.com/tinywrkb/flatpaks/commit/cbdccf8dadd1f8f4ade8fa765bf1c7d8efad60e2#diff-a336c65b3303264e31ca75eb080beb719f1b08f668d33eff7d63d2dcabd8cb35).  
Because RealtimeKit is broken with Flatpak apps and PipeWire's rtkit module might have been too verbose [I switched to building an updated PipeWire version](https://github.com/tinywrkb/flatpaks/commit/c1d475ef69b92049cff26f5954ae5308aafe3ee5#diff-a336c65b3303264e31ca75eb080beb719f1b08f668d33eff7d63d2dcabd8cb35), I'm not sure if this needed with PipeWire 0.3.23.
