### ISSUE TITLE
question: virtual camera support in flatpak

### ISSUE THREAD

**Issue by soredake** [flathub/com.obsproject.Studio#91]
OBS 26.1 will support virtual camera output on Linux, and it requires v4l2loopback module, so how is it gonna work with flatpak?
https://github.com/obsproject/obs-studio/releases/tag/26.1.0-rc1

**Comment by GeorgesStavracas** [comment]
I don't think it can be supported in Flatpak, unfortunately. The only way something like this can work is by using PipeWire to export a camera, but it may take a long time for it to happen...

**Comment by GeorgesStavracas** [comment]
I proved myself wrong and managed to craft [an upstream PR making the V4L2 implementation of VirtualCam support Flatpak](https://github.com/obsproject/obs-studio/pull/4552). It's not ideal since it uses flatpak-spawn to run a couple of unsandboxed commands, but at least we can have this feature working for now :slightly_smiling_face: 

I'll go ahead and close this issue since it's being addressed upstream, and if we're lucky, it'll be merged before the OBS Studio 27 release.

**Comment by GeorgesStavracas** [comment]
And seems like we **are** lucky! \o/   obsproject/obs-studio#4552 landed just in time for the 27 release.
